export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
export const LOAD_PRODUCT_MODAL = "LOAD_PRODUCT_MODAL";
export const REMOVE_PRODUCT_MODAL = "REMOVE_PRODUCT_MODAL";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";



